services:
  tg_parser:
    build:
      dockerfile: Dockerfile
    command: poetry run uvicorn __main__:app --host 0.0.0.0 --port 8002
    env_file:
      - .env
networks:
  default:
    name: tg_parser-network
