services:
  tg_parser:
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./app:/app/app
      - ~/vityaz_site/backups:/app/app/backups
      - ~/vityaz_site/media:/app/app/backups/media
    env_file:
      - .env
    networks:
      tg_parser-network:
        aliases:
          - tg_parser

networks:
  tg_parser-network:
    external: true
