name: Deploy workflow
on: 
  push:
    branches: [ main ]
  repository_dispatch:
    types: [deploy_trigger]
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deploy
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Сохраняем текущий UID и GID
            CURRENT_UID=$(id -u)
            CURRENT_GID=$(id -g)
            
            # Проверяем существование директории
            if [ -d "~/fastAPI-microservice" ]; then
                echo "Directory exists, performing update"
                cd ~/fastAPI-microservice
                # Останавливаем контейнеры
                docker compose down || true
                # Обновляем репозиторий
                git pull
            else
                echo "Directory does not exist, performing clone"
                # Клонирование репозитория
                git clone --depth 1 https://${{ secrets.GH_TOKEN }}@github.com/HRAON88/fastAPI-microservice.git
                cd fastAPI-microservice
            fi
            
            # Создание .env файла
            cat > .env << EOF
            API_ID=${{ secrets.API_ID }}
            API_HASH=${{ secrets.API_HASH }}
            SESSION_STRING=${{ secrets.SESSION_STRING }}
            UID=$CURRENT_UID
            GID=$CURRENT_GID
            EOF
            
            # Сборка и запуск контейнеров
            DOCKER_BUILDKIT=1 docker compose build \
              --build-arg UID=$CURRENT_UID \
              --build-arg GID=$CURRENT_GID
            docker compose up -d
            
            # Очистка неиспользуемых образов
            docker image prune -f
